/// Polices proposées dans l’éditeur de thème personnalisé.
const kQuoteEditorFontFamilies = <String>[
  'InterTight',
  'YesevaOne',
  'DidactGothic',
  'JosefinSlab',
  'Raleway',
  'AbhayaLibre',
  'Allerta',
  'BebasNeue',
  'BodoniModa',
  'CormorantGaramond',
  'EBGaramond',
  'JosefinSans',
  'Lato',
  'LibreBaskerville',
  'Lustria',
  'MontSerrat',
  'Oranlenbaum',
  'Oswald',
  'Ovo',
  'PlayfairDisplay',
  'Quicksand',
  'Sanchez',
  'SourceSansPro',
  'Volkorn',
];
